relationships = {'NO_RELATIONSHIP': 0, 'SAME_AS': 1, 'INSIDE': 2, 'SERVES': 3}
relationships_text = {0: 'no relationship', 1: 'same as', 2: 'inside', 3: 'serves'}
model_names = {'bert': 'bert-base-uncased', 'distilbert': 'distilbert-base-uncased', 'roberta': 'roberta-base'}
default_model = 'bert'
n_relationships = 4
max_seq_len = 128
device = 'cpu'
dropout = 0.1
epochs = 3
batch_size = 32
hidden_size = 768
co_emb = 256
lr = 3e-5
error_d = 1000
max_d_filter = 1000
rep_thr = 0.7
rep_diff = 0.1
path_prefix = "data/"
kgc_path = "KGC/"
classification_path = "Classification/"
path_suffix = ".csv"
save_path_kgc = "saved_models/kgc_model.pkl"
save_path_classification = "saved_models/classifier.pkl"
glove_url = "http://nlp.stanford.edu/data/glove.6B.zip"
glove_folder = "glove/"
glove_zip = "glove.6B.zip"
glove_file = "glove.6B."
glove_size = 100    # [50, 100, 200, 300]
